version: "2"

# Fai il boostrap del progetto così:
# 1. modifica le impostazioni di connessione al db su setting.php
# MYSQL_ROOT_PASSWORD: password
# MYSQL_DATABASE: drupal
# MYSQL_USER: drupal
# MYSQL_PASSWORD: drupal
# 2. Crea la dir /mariadb-init e inseiri lì il dump del db .sql
# 3. avvia il docker compose
# $ docker-compose up (verifica dai log che stia caricando il db oppure usa il parametro "-d" per eseguire docker-compose come demone)

services:
  db:
    image: mysql:5.7.25
    container_name: "labimus_db_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    container_name: "labimus_php"
#    image: wodby/drupal-php:7.0-2.0.0
    image: wodby/drupal-php:7.1-2.0.0
#    image: wodby/drupal-php:5.6-2.0.0
#    image: wodby/drupal-php:5.3-2.0.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./:/var/www/html

  nginx:
    container_name: "labimus_nginx"
#    image: wodby/drupal-nginx:8-1.10-2.0.0
    image: wodby/drupal-nginx:7-1.10-2.0.0
#    image: wodby/drupal-nginx:6-1.10-2.0.0
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/public
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"

#  redis:
#    container_name: "labimus_redis"
#    image: wodby/redis:3.2-2.0.1

  pma:
    container_name: "labimus_pma"
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      PHP_UPLOAD_MAX_FILESIZE: 5G
      PHP_MAX_INPUT_VARS: 5G
    ports:
      - "7777:80"

  adminer:
    container_name: "labimus_adminer"
    image: adminer
    ports:
      - "8080:8080"
